Miscellaneous fixes.

diff --git a/apply-postgresql b/apply-postgresql
--- a/apply-postgresql
+++ b/apply-postgresql
@@ -50,31 +50,36 @@ while [ "$MIG_BASEDIR" == "" ]; do
     read -ep "Migrations dir: " MIG_BASEDIR
 done
 
-POSTGRESQL_CMD="echo $DB_PASSWORD | /usr/bin/psql --host $DB_HOST --username $DB_USERNAME --password --tuples-only --dbname $DB_NAME "
+exec_sql() {
+    PGPASSWORD=$DB_PASSWORD /usr/bin/psql --quiet --host=$DB_HOST --username=$DB_USERNAME --pset=pager=off --pset=tuples_only --dbname=$DB_NAME --command="$@" 2>/dev/null
+}
+
+exec_sql_file() {
+    output=$(PGPASSWORD=$DB_PASSWORD /usr/bin/psql --quiet --host=$DB_HOST --username=$DB_USERNAME --pset=pager=off --pset=tuples_only --dbname=$DB_NAME < $1)
+    echo $output >&2
+    retval=$(echo $output | wc -l)
+    return $retval
+}
 
 # First, try to connect
 query="\q"
-echo "$query" | $POSTGRESQL_CMD
+exec_sql "$query"
 retval=$?
 if [ ! $retval -eq 0 ]; then
+    LOG_FATAL "Could not connect to database."
     exit $retval;
 fi
 
-
-exit
-
-
 # Check if migration version table exists
-LOG_DEBUG "Checking if migration version table $MIG_VERSION_TABLE exists..."
-exists=$(echo "SHOW TABLES LIKE '$MIG_VERSION_TABLE_NAME'" \
-    | $POSTGRESQL_CMD \
-    | wc -l)
+LOG_DEBUG "Checking if migration version table $MIG_VERSION_TABLE_NAME exists..."
+exists=$(exec_sql "\d $MIG_VERSION_TABLE_NAME")
+retval=$?
 
 # Create table if it does not exist
-if [ $exists -eq 0 ]; then
+if [ $retval -ne 0 ]; then
     LOG_DEBUG "Table does not exist. Creating..."
     query="CREATE TABLE $MIG_VERSION_TABLE_NAME ( version BIGINT NOT NULL PRIMARY KEY )"
-    echo "$query" | $POSTGRESQL_CMD
+    exec_sql "$query"
 
     retval=$?
     if [ $retval -ne 0 ]; then
@@ -86,86 +91,93 @@ fi
 
 # Get current migration version
 query="SELECT version FROM $MIG_VERSION_TABLE_NAME"
-db_version=$(echo "$query" | $POSTGRESQL_CMD)
+db_version=$(exec_sql "$query")
 
 if [ "$db_version" == "" ]; then
     db_version=0
     LOG_DEBUG "Initializing DB version..."
     query="INSERT INTO $MIG_VERSION_TABLE_NAME VALUES($db_version)"
-    echo "$query" | $POSTGRESQL_CMD
+    exec_sql "$query"
 
     retval=$?
     if [ $retval -ne 0 ]; then
-    LOG_FATAL "Failed to initialize  migration version table in DB. "
-    exit $retval
+	LOG_FATAL "Failed to initialize  migration version table in DB. "
+	exit $retval
     fi
 
 fi
-
-#db_version=20120206155550163
 
 # Figure out which migrations need to be applied
 dir=$MIG_BASEDIR/$DB_NAME
-all_migs=$(find $dir -type d -name [0-9]* -maxdepth 1 -mindepth 1 | sort -n)
-applicable_migs=""
-for mig in $all_migs; do
-    mig_version=$(basename $mig)
-    if [ $mig_version -gt $db_version ]; then
-    applicable_migs="$applicable_migs $mig"
+if [ -d $dir ]; then
+    all_migs=$(find $dir -maxdepth 1 -mindepth 1 -type d -name [0-9]* | sort -n)
+    applicable_migs=""
+    for mig in $all_migs; do
+	mig_version=$(basename $mig)
+	if [ $mig_version -gt $db_version ]; then
+	    applicable_migs="$applicable_migs $mig"
+	fi
+    done
+    
+    # Quit if there are no migrations to apply
+    if [ "$applicable_migs" == "" ]; then
+	echo "All migrations already applied. Nothing to do."
+	exit
     fi
-done
+    
+    # TODO: Backup DB
+    
+    # Apply migrations, in order
+    error=0
+    for mig in $applicable_migs; do
 
-# Quit if there are no migrations to apply
-if [ "$applicable_migs" == "" ]; then
-    echo "All migrations already applied. Nothing to do."
-    exit
-fi
+	if [ $error -eq 0 ]; then
+	    mig_version=$(basename $mig)
+	    up_file="$mig/up"
+	    
+	    echo "Applying migration version=$mig_version..."
+	    
+	    if [ -f "$up_file" ]; then
+		LOG_DEBUG "Applying UP migration file $up_file..."
+		exec_sql_file $up_file
+		retval=$?
+		
+		if [ $retval -eq 0 ]; then
+		    
+		    LOG_DEBUG "Successfully applied migration $up_file. Updating version in DB to $mig_version..."
+		    
+                    # Update version table in DB
+	            query="UPDATE $MIG_VERSION_TABLE_NAME SET version=$mig_version"
+		    exec_sql "$query"
+		    retval=$?
+		    
+		    if [ $retval -eq 0 ]; then
+			LOG_DEBUG "Successfully updated DB version to $mig_version."
+		    else
+			LOG_DEBUG "Failed to update DB version to $mig_version."
+			error=102
+		    fi
+		    
+		else
+		    
+		    LOG_DEBUG "Failed to apply migration $up_file."
+		    error=103
+		    
+		fi
+	    
+	    else
+		error=101
+	    fi
+	fi
 
-# TODO: Backup DB
+    done
 
-# Apply migrations, in order
-error=0
-for mig in $applicable_migs; do
-
-    mig_version=$(basename $mig)
-    up_file="$mig/up"
-
-    if [ -f "$up_file" ]; then
-    LOG_DEBUG "Applying UP migration file $up_file..."
-    $POSTGRESQL_CMD < $up_file
-    retval=$?
-
-    if [ $retval -eq 0 ]; then
-
-        LOG_DEBUG "Successfully applied migration $up_file. Updating version in DB to $mig_version..."
-
-	    # Update version table in DB
-	        query="UPDATE $MIG_VERSION_TABLE_NAME SET version=$mig_version"
-		    echo "$query" | $POSTGRESQL_CMD
-		        retval=$?
-
-			    if [ $retval -eq 0 ]; then
-			       LOG_DEBUG "Successfully updated DB version to $mig_version."
-			           else
-					LOG_DEBUG "Failed to update DB version to $mig_version."
-						  error=102
-						      fi
-
-						      else
-
-						          LOG_DEBUG "Failed to apply migration $up_file."
-							      error = 103
-
-							      fi
-
-    else
-    error=101
+    # Rollback if there were errors
+    if [ $error -ne 0 ]; then
+        # TODO: Restore DB from backup
+	exit $error
     fi
 
-done
-
-# Rollback if there were errors
-if [ $error -ne 0 ]; then
-    # TODO: Restore DB from backup
-    exit $error
+else
+    echo "No migrations for db = $DB_NAME found. Nothing to do."
 fi
