Updated to delete backup file under most circumstances.

diff --git a/apply-postgresql b/apply-postgresql
--- a/apply-postgresql
+++ b/apply-postgresql
@@ -174,8 +174,8 @@ if [ -d $dir ]; then
     PGPASSWORD=$DB_PASSWORD pg_dump --format=tar --schema=public --file=$DB_BACKUP_FILENAME --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME $DB_NAME
     retval=$?
     if [ $retval -ne 0 ]; then
-	LOG_FATAL "Could not create database backup. Not safe to attempt migrations."
-	exit $retval
+	    LOG_FATAL "Could not create database backup. Not safe to attempt migrations."
+    	exit $retval
     fi
 
     # Apply migrations, in order
@@ -214,10 +214,10 @@ if [ -d $dir ]; then
 		    retval=$?
 		    
 		    if [ $retval -eq 0 ]; then
-			LOG_DEBUG "Successfully updated DB version to $mig_version."
+			    LOG_DEBUG "Successfully updated DB version to $mig_version."
 		    else
-			LOG_FATAL "Failed to update DB version to $mig_version."
-			error=102
+			    LOG_FATAL "Failed to update DB version to $mig_version."
+			    error=102
 		    fi
 		    
 		else
@@ -228,7 +228,7 @@ if [ -d $dir ]; then
 		fi
 		
 	    else
-		error=101
+		    error=101
 	    fi
 	fi
 
@@ -237,30 +237,40 @@ if [ -d $dir ]; then
     # Rollback if there were errors
     if [ $error -ne 0 ]; then
 
-	# Drop all sequences
-	drop_sequences_stmts=$(PGPASSWORD=$DB_PASSWORD psql --quiet --tuples-only --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME $DB_NAME --command="SELECT 'DROP SEQUENCE ' || sequence_name || ' CASCADE;' FROM information_schema.sequences WHERE sequence_schema='public'")
+	    # Drop all sequences
+	    drop_sequences_stmts=$(PGPASSWORD=$DB_PASSWORD psql --quiet --tuples-only --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME $DB_NAME --command="SELECT 'DROP SEQUENCE ' || sequence_name || ' CASCADE;' FROM information_schema.sequences WHERE sequence_schema='public'")
 
-	# Drop all tables 
-	drop_tables_stmts=$(PGPASSWORD=$DB_PASSWORD psql --quiet --tuples-only --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME $DB_NAME --command="SELECT 'DROP TABLE ' || table_name || ' CASCADE;' FROM information_schema.tables WHERE table_schema='public' AND table_type != 'VIEW' AND table_name NOT LIKE 'pg_ts_%%'")
+	    # Drop all tables 
+    	drop_tables_stmts=$(PGPASSWORD=$DB_PASSWORD psql --quiet --tuples-only --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME $DB_NAME --command="SELECT 'DROP TABLE ' || table_name || ' CASCADE;' FROM information_schema.tables WHERE table_schema='public' AND table_type != 'VIEW' AND table_name NOT LIKE 'pg_ts_%%'")
 
-	echo -e "$drop_sequences_stmts\n$drop_tables_stmts" | PGPASSWORD=$DB_PASSWORD psql --quiet --host=$DB_HOST --port=$DB_PORT --username $DB_USERNAME $DB_NAME 2>/dev/null
-	retval=$?
-	if [ $retval -ne 0 ]; then
-	    LOG_DEBUG "Rollback return code = $retval"
-	    LOG_FATAL "Could not rollback. Database may be in an inconsistent state!"
-	    exit 201
-	fi
+    	echo -e "$drop_sequences_stmts\n$drop_tables_stmts" | PGPASSWORD=$DB_PASSWORD psql --quiet --host=$DB_HOST --port=$DB_PORT --username $DB_USERNAME $DB_NAME 2>/dev/null
+    	retval=$?
+    	if [ $retval -ne 0 ]; then
+    	    LOG_DEBUG "Rollback return code = $retval"
+    	    LOG_FATAL "Could not rollback. Database may be in an inconsistent state!"
+    	    LOG_FATAL "Backup file located at: $DB_BACKUP_FILENAME"
+	        exit 201
+    	fi
 
         # Restore DB from backup
-	PGPASSWORD=$DB_PASSWORD pg_restore --create --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME --dbname=$DB_NAME $DB_BACKUP_FILENAME #2>/dev/null
-	retval=$?
-	if [ $retval -ne 0 ]; then
-	    LOG_FATAL "Could not rollback. Database may be in an inconsistent state!"
-	    exit 202
-	fi
+    	PGPASSWORD=$DB_PASSWORD pg_restore --create --host=$DB_HOST --port=$DB_PORT --username=$DB_USERNAME --dbname=$DB_NAME $DB_BACKUP_FILENAME #2>/dev/null
+    	retval=$?
+	    if [ $retval -ne 0 ]; then
+	        LOG_FATAL "Could not rollback. Database may be in an inconsistent state!"
+	        LOG_FATAL "Backup file located at: $DB_BACKUP_FILENAME"
+    	    exit 202
+    	fi
 
-	echo "Rolled back database (version = $db_version) from backup."
-	exit $error
+        # Delete the backup file
+        rm $DB_BACKUP_FILENAME
+
+	    echo "Rolled back database (version = $db_version) from backup."
+    	exit $error
+    else
+    
+        # Delete the backup file
+        rm $DB_BACKUP_FILENAME
+        
     fi
 
 else
