Exit if timestamp cannot be generated.

diff --git a/create b/create
--- a/create
+++ b/create
@@ -53,13 +53,18 @@ get_daytime_line() {
 	    sleep $RETRY_INTERVAL
     done
 
-    LOG_FATAL "Could not get DAYTIME line from servers in $DAYTIME_MAX_ATTEMPTS attempts. Giving up."
+    LOG_DEBUG "Could not get DAYTIME line from servers in $DAYTIME_MAX_ATTEMPTS attempts. Giving up."
     exit 1
 }
 
 get_timestamp() {
 
     daytime_line=$(get_daytime_line)
+    retval=$?
+    if [ $retval -ne 0 ]; then
+	exit $retval;
+    fi
+
     echo $daytime_line | awk '{printf "20%s%s%03d",$2,$3,$7}' | sed 's/[-:]//g'
 
 }
@@ -111,6 +116,11 @@ fi
 
 # Generate timestamp
 timestamp=$(get_timestamp)
+retval=$?
+if [ $retval -ne 0 ]; then
+    LOG_FATAL "Could not generate unique timestamp for migration."
+    exit $retval;
+fi
 
 # Create directories
 dir=$BASEDIR/$DB_NAME/$timestamp
